name: My first workflow
on: push
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Github Action
        run: echo "Hello this is first workflow in github action"
      - name: Bye Github Action
        run: echo "Bye Bye github action"
